# Generated by Django 5.2.17 on 2026-09-11 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=16, unique=True)),
                ('cik', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['ticker'],
            },
        ),
        migrations.CreateModel(
            name='EmbeddingVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='ollama', max_length=50)),
                ('model_name', models.CharField(max_length=255)),
                ('dimensions', models.PositiveIntegerField()),
                ('chunker_version', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('provider', 'model_name', 'dimensions', 'chunker_version'), name='uq_embedding_version')],
            },
        ),
        migrations.CreateModel(
            name='Filing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accession_number', models.CharField(max_length=32)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('form', models.CharField(max_length=10)),
                ('filing_date', models.DateField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('primary_document', models.CharField(blank=True, max_length=255)),
                ('source_url', models.URLField(blank=True, max_length=1000)),
                ('local_path', models.TextField()),
                ('content_sha256', models.CharField(blank=True, max_length=64)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('ingestion_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('indexed', 'Indexed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='filings', to='watcher.company')),
            ],
        ),
        migrations.CreateModel(
            name='FilingChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.PositiveIntegerField()),
                ('item_number', models.CharField(blank=True, db_index=True, max_length=32)),
                ('section_title', models.CharField(blank=True, max_length=500)),
                ('text', models.TextField()),
                ('content_sha256', models.CharField(db_index=True, max_length=64)),
                ('char_start', models.PositiveIntegerField(blank=True, null=True)),
                ('char_end', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('embedding_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chunks', to='watcher.embeddingversion')),
                ('filing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='watcher.filing')),
            ],
            options={
                'ordering': ['filing_id', 'chunk_index'],
            },
        ),
        migrations.CreateModel(
            name='IngestionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_job', to='watcher.filing')),
            ],
        ),
        migrations.AddIndex(
            model_name='filing',
            index=models.Index(fields=['company', 'form', 'filing_date'], name='idx_filing_lookup'),
        ),
        migrations.AddConstraint(
            model_name='filing',
            constraint=models.UniqueConstraint(fields=('company', 'accession_number', 'sequence'), name='uq_filing_identity'),
        ),
        migrations.AddConstraint(
            model_name='filingchunk',
            constraint=models.UniqueConstraint(fields=('filing', 'chunk_index'), name='uq_filing_chunk'),
        ),
    ]
