# Generated by Django 5.2.17 on 2026-09-12 04:39

import django.db.models.deletion
# import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filingchunk',
            name='embedding_version',
        ),
        migrations.AlterField(
            model_name='filing',
            name='ingestion_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('chunked', 'Chunked'), ('indexed', 'Indexed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='ChunkEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # ('vector', pgvector.django.vector.VectorField(dimensions=768)),
                ('vector', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='watcher.filingchunk')),
                ('embedding_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chunk_embeddings', to='watcher.embeddingversion')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('chunk', 'embedding_version'), name='uq_chunk_embedding_version')],
            },
        ),
    ]
