# Generated by Django 5.2.17 on 2026-09-12 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0002_remove_filingchunk_embedding_version_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.CharField(blank=True, max_length=32)),
                ('document_type', models.CharField(blank=True, db_index=True, max_length=32)),
                ('document_name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('source_url', models.URLField(blank=True, max_length=1000)),
                ('local_path', models.TextField(blank=True)),
                ('content_sha256', models.CharField(blank=True, db_index=True, max_length=64)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('is_primary', models.BooleanField(db_index=True, default=False)),
                ('downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='watcher.filing')),
            ],
            options={
                'ordering': ['filing_id', 'sequence', 'id'],
            },
        ),
        migrations.AddField(
            model_name='filingchunk',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='watcher.filingdocument'),
        ),
        migrations.AddIndex(
            model_name='filingdocument',
            index=models.Index(fields=['filing', 'document_type'], name='idx_filing_document_type'),
        ),
        migrations.AddConstraint(
            model_name='filingdocument',
            constraint=models.UniqueConstraint(fields=('filing', 'sequence', 'document_name'), name='uq_filing_document_identity'),
        ),
    ]
