# Generated by Django 5.2.17 on 2026-09-12 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0003_filingdocument_filingchunk_document_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='filingchunk',
            name='uq_filing_chunk',
        ),
        migrations.AddConstraint(
            model_name='filingchunk',
            constraint=models.UniqueConstraint(fields=('document', 'chunk_index'), name='uq_document_chunk'),
        ),
    ]
