# Generated by Django 5.2.17 on 2026-09-14 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0004_remove_filingchunk_uq_filing_chunk_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=255)),
                ('normalized_alias', models.CharField(db_index=True, max_length=255)),
                ('source', models.CharField(default='system', max_length=50)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='watcher.company')),
            ],
            options={
                'ordering': ['company_id', 'normalized_alias'],
                'indexes': [models.Index(fields=['normalized_alias', 'is_active'], name='idx_company_alias_lookup')],
                'constraints': [models.UniqueConstraint(fields=('company', 'normalized_alias'), name='uq_company_normalized_alias')],
            },
        ),
    ]
