# Generated by Django 5.2.17 on 2026-09-15 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0006_filingsummarycache'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSummaryCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_signature', models.CharField(db_index=True, max_length=64)),
                ('model_name', models.CharField(max_length=255)),
                ('prompt_version', models.CharField(max_length=50)),
                ('summary', models.TextField()),
                ('chunk_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary_cache', to='watcher.filingdocument')),
            ],
            options={
                'indexes': [models.Index(fields=['model_name', 'prompt_version'], name='idx_document_summary_version')],
            },
        ),
    ]
