# Generated by Django 5.2.17 on 2026-09-17 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0007_documentsummarycache'),
    ]

    operations = [
        migrations.AddField(
            model_name='filing',
            name='entry_session',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
