# Generated by Django 5.2.17 on 2026-09-18 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0009_automationrun_filing_automation_run'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationrun',
            name='status',
            field=models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('partial', 'Partial'), ('failed', 'Failed')], default='running', max_length=20),
        ),
    ]
