# Generated by Django 5.2.17 on 2026-09-18 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0010_alter_automationrun_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(default='daily', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('sync_zone', models.BooleanField(default=False)),
                ('daily_recur', models.IntegerField(default=1)),
                ('weekly_recur', models.IntegerField(default=1)),
                ('weekly_days', models.JSONField(default=dict)),
                ('monthly_type', models.CharField(default='days', max_length=20)),
                ('monthly_months', models.CharField(default='All months', max_length=50)),
                ('monthly_days', models.CharField(default='1', max_length=100)),
                ('monthly_on_week', models.CharField(default='First', max_length=20)),
                ('monthly_on_day', models.CharField(default='Sunday', max_length=20)),
                ('run_count', models.IntegerField(default=1)),
                ('run_times', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Schedule Config',
            },
        ),
    ]
