# Generated by Django 5.2.17 on 2026-09-19 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0011_scheduleconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='filing',
            name='item_codes_match',
            field=models.BooleanField(blank=True, help_text='Whether SEC reported items match parsed item codes.', null=True),
        ),
        migrations.AddField(
            model_name='filing',
            name='parsed_item_codes',
            field=models.TextField(blank=True, default='', help_text='Item codes extracted by internal parser. Example: 1.01;9.01'),
        ),
        migrations.AddField(
            model_name='filing',
            name='sec_item_codes',
            field=models.TextField(blank=True, default='', help_text='SEC reported 8-K item codes. Example: 1.01;9.01'),
        ),
    ]
