# Generated by Django 5.2.17 on 2026-09-19 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0012_filing_item_codes_match_filing_parsed_item_codes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailureEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('download', 'Download'), ('metadata', 'Metadata'), ('registration', 'Registration'), ('indexing', 'Indexing'), ('summary', 'Summary'), ('email', 'Email'), ('ingestion', 'Ingestion')], max_length=30)),
                ('code', models.CharField(choices=[('unknown', 'Unknown'), ('download_failed', 'Download Failed'), ('metadata_failed', 'Metadata Failed'), ('registration_failed', 'Registration Failed'), ('index_failed', 'Index Failed'), ('summary_failed', 'Summary Failed'), ('email_failed', 'Email Failed'), ('ingestion_failed', 'Ingestion Failed')], default='unknown', max_length=50)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('filing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='failure_events', to='watcher.filing')),
            ],
        ),
    ]
