# Generated by Django 5.2.17 on 2026-09-19 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0013_failureevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='filing',
            name='flag',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='filing',
            name='flag_reason',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
