# Generated by Django 5.2.17 on 2026-09-19 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0014_filing_flag_filing_flag_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='filing',
            name='amends',
            field=models.OneToOneField(blank=True, help_text='The original filing this amendment supersedes', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amended_by', to='watcher.filing'),
        ),
        migrations.AddField(
            model_name='filing',
            name='report_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
