# Generated by Django 5.2.17 on 2026-09-21 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0015_filing_amends_filing_report_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filing',
            name='amends',
            field=models.ForeignKey(blank=True, help_text='The original filing this amendment supersedes', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amended_by', to='watcher.filing'),
        ),
    ]
