# Generated by Django 5.2.17 on 2026-09-21 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0016_alter_filing_amends'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationrun',
            name='unlinked_amendments_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
