# Generated by Django 5.2.17 on 2026-09-21 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0017_automationrun_unlinked_amendments_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationrun',
            name='shards_expected',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='automationrun',
            name='shards_parsed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='failureevent',
            name='code',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('shard_fetch_failed', 'Shard Fetch Failed'), ('download_failed', 'Download Failed'), ('metadata_failed', 'Metadata Failed'), ('registration_failed', 'Registration Failed'), ('index_failed', 'Index Failed'), ('summary_failed', 'Summary Failed'), ('email_failed', 'Email Failed'), ('ingestion_failed', 'Ingestion Failed')], default='unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='failureevent',
            name='stage',
            field=models.CharField(choices=[('discovery', 'Discovery'), ('download', 'Download'), ('metadata', 'Metadata'), ('registration', 'Registration'), ('indexing', 'Indexing'), ('summary', 'Summary'), ('email', 'Email'), ('ingestion', 'Ingestion')], max_length=30),
        ),
    ]
