# Generated by Django 5.2.17 on 2026-09-21 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0018_automationrun_shards_expected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filing',
            name='entry_rule',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
    ]
