# Generated by Django 5.2.17 on 2026-09-21 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0019_filing_entry_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='failureevent',
            name='resolved_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='filing',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
