# Generated by Django 5.2.17 on 2026-09-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0020_failureevent_resolved_at_filing_email_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationrun',
            name='ambiguous_amendments_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
