# Generated by Django 5.2.17 on 2026-09-24 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0022_normalize_item_codes'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMTPConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(blank=True, max_length=200)),
                ('host', models.CharField(max_length=253)),
                ('port', models.PositiveIntegerField(default=587)),
                ('security', models.CharField(choices=[('TLS', 'TLS'), ('STARTTLS', 'STARTTLS'), ('SSL', 'SSL'), ('NONE', 'None')], default='TLS', max_length=10)),
                ('username', models.CharField(blank=True, max_length=254)),
                ('sender_email', models.EmailField(max_length=254)),
                ('reply_to_email', models.EmailField(blank=True, max_length=254)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SMTP configuration',
                'verbose_name_plural': 'SMTP configuration',
            },
        ),
    ]
