# Generated by Django 5.2.17 on 2026-09-26 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


LABELLER_GROUP = "labeller"


def create_labeller_group(apps, schema_editor):
    # Guide 4.2: interns label through this group. Staff users can label
    # too; being in the group grants nothing else.
    Group = apps.get_model("auth", "Group")
    Group.objects.get_or_create(name=LABELLER_GROUP)


def remove_labeller_group(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(name=LABELLER_GROUP).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0026_totpdevice_backupcode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroundTruthSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('split', models.CharField(choices=[('train', 'Train'), ('test', 'Test'), ('sealed', 'Sealed')], max_length=10)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('filing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ground_truth_split', to='watcher.filing')),
            ],
        ),
        migrations.CreateModel(
            name='LabellingSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stratum', models.CharField(blank=True, help_text='Primary item code the filing was sampled under.', max_length=32)),
                ('required_labels', models.PositiveSmallIntegerField(default=1)),
                ('position', models.PositiveIntegerField(db_index=True)),
                ('taxonomy_version', models.CharField(max_length=20)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('filing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='labelling_sample', to='watcher.filing')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='GroundTruthLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxonomy_version', models.CharField(max_length=20)),
                ('is_material', models.BooleanField()),
                ('category', models.CharField(blank=True, max_length=40)),
                ('confidence', models.PositiveSmallIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('labelled_at', models.DateTimeField(auto_now_add=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('filing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ground_truth_labels', to='watcher.filing')),
                ('labeller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ground_truth_labels', to=settings.AUTH_USER_MODEL)),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='watcher.groundtruthlabel')),
            ],
            options={
                'indexes': [models.Index(fields=['filing', 'labeller'], name='watcher_gro_filing__ed4b7b_idx')],
            },
        ),
        migrations.RunPython(
            create_labeller_group,
            remove_labeller_group,
        ),
    ]
