# Generated by Django 5.2.17 on 2026-09-26 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0027_ground_truth'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterpreterRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('partial', 'Partial'), ('failed', 'Failed')], default='running', max_length=20)),
                ('taxonomy_version', models.CharField(max_length=20)),
                ('prompt_version', models.CharField(max_length=20)),
                ('model_name', models.CharField(max_length=200)),
                ('filings_selected', models.PositiveIntegerField(default=0)),
                ('classified_count', models.PositiveIntegerField(default=0)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='FilingClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxonomy_version', models.CharField(max_length=20)),
                ('prompt_version', models.CharField(max_length=20)),
                ('model_name', models.CharField(max_length=200)),
                ('model_options', models.JSONField(default=dict)),
                ('is_material', models.BooleanField(null=True)),
                ('category', models.CharField(blank=True, max_length=40)),
                ('confidence', models.FloatField(null=True)),
                ('reasoning', models.TextField(blank=True)),
                ('body_item_numbers', models.CharField(blank=True, max_length=200)),
                ('extracted_facts', models.JSONField(default=dict)),
                ('needs_human_review', models.BooleanField(default=False)),
                ('failure_code', models.CharField(blank=True, max_length=40)),
                ('raw_response', models.TextField(blank=True)),
                ('input_sha256', models.CharField(max_length=64)),
                ('input_truncated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('filing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='watcher.filing')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classifications', to='watcher.interpreterrun')),
            ],
        ),
        migrations.CreateModel(
            name='ClassificationOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxonomy_version', models.CharField(max_length=20)),
                ('is_material', models.BooleanField()),
                ('category', models.CharField(blank=True, max_length=40)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classification_overrides', to=settings.AUTH_USER_MODEL)),
                ('classification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='override', to='watcher.filingclassification')),
            ],
        ),
        migrations.AddIndex(
            model_name='filingclassification',
            index=models.Index(fields=['filing', '-created_at'], name='watcher_fil_filing__e53cac_idx'),
        ),
        migrations.AddIndex(
            model_name='filingclassification',
            index=models.Index(fields=['taxonomy_version', 'prompt_version'], name='watcher_fil_taxonom_33bc5f_idx'),
        ),
        migrations.AddIndex(
            model_name='filingclassification',
            index=models.Index(fields=['needs_human_review'], name='watcher_fil_needs_h_c4ca10_idx'),
        ),
    ]
