# Generated by Django 5.2.17 on 2026-09-26 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0029_failureevent_interpreter_stage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditorRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('partial', 'Partial'), ('failed', 'Failed')], default='running', max_length=20)),
                ('taxonomy_version', models.CharField(max_length=20)),
                ('auditor_prompt_version', models.CharField(max_length=20)),
                ('auditor_model_name', models.CharField(max_length=200)),
                ('sampled_count', models.PositiveIntegerField(default=0)),
                ('classification_checked', models.PositiveIntegerField(default=0)),
                ('summary_checked', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auditor_category', models.CharField(blank=True, max_length=40)),
                ('auditor_is_material', models.BooleanField(null=True)),
                ('auditor_confidence', models.FloatField(null=True)),
                ('category_agreed', models.BooleanField(null=True)),
                ('material_agreed', models.BooleanField(null=True)),
                ('failure_code', models.CharField(blank=True, max_length=40)),
                ('summary_claims_total', models.PositiveIntegerField(default=0)),
                ('summary_claims_grounded', models.PositiveIntegerField(default=0)),
                ('ungrounded_claims', models.JSONField(default=list)),
                ('is_sealed', models.BooleanField(default=False)),
                ('input_sha256', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_samples', to='watcher.filingclassification')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='watcher.auditorrun')),
            ],
            options={
                'indexes': [models.Index(fields=['run', 'category_agreed'], name='watcher_aud_run_id_1923b5_idx'), models.Index(fields=['classification'], name='watcher_aud_classif_c1c6a4_idx'), models.Index(fields=['is_sealed'], name='watcher_aud_is_seal_1adf46_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('taxonomy_version', models.CharField(max_length=20)),
                ('interpreter_prompt_version', models.CharField(blank=True, max_length=20)),
                ('interpreter_model_name', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(blank=True, max_length=40)),
                ('sample_size', models.PositiveIntegerField()),
                ('agreement_rate', models.FloatField()),
                ('material_agreement_rate', models.FloatField(null=True)),
                ('grounding_rate', models.FloatField(null=True)),
                ('is_sealed', models.BooleanField(default=False)),
                ('below_bar', models.BooleanField(default=False)),
                ('alarmed_at', models.DateTimeField(blank=True, null=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='windows', to='watcher.auditorrun')),
            ],
            options={
                'ordering': ['-period_end', 'category'],
                'indexes': [models.Index(fields=['category', '-period_end'], name='watcher_aud_categor_3c95b6_idx'), models.Index(fields=['below_bar'], name='watcher_aud_below_b_904d59_idx')],
            },
        ),
    ]
