"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import secrets
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# ---------------------------------------------------------------------
# .env loading
#
# This project has NO python-dotenv dependency (see requirements.txt),
# so we load backend/.env with the standard library only.
#
# Rules:
#   - real environment variables always win over .env
#   - blank lines and "#" comments are ignored
#   - "export KEY=value" is accepted
#   - surrounding single/double quotes are stripped
# ---------------------------------------------------------------------

def _load_env_file(env_path: Path) -> None:
    if not env_path.is_file():
        return

    try:
        raw_text = env_path.read_text(encoding="utf-8-sig")
    except (OSError, UnicodeDecodeError):
        return

    for raw_line in raw_text.splitlines():
        line = raw_line.strip()

        if not line or line.startswith("#"):
            continue

        if line.lower().startswith("export "):
            line = line[len("export "):].strip()

        if "=" not in line:
            continue

        key, _, value = line.partition("=")

        key = key.strip()
        value = value.strip()

        if len(value) >= 2 and value[0] == value[-1] and value[0] in ("'", '"'):
            value = value[1:-1]

        if key and key not in os.environ:
            os.environ[key] = value


_load_env_file(BASE_DIR / ".env")


def _env_str(name, default=""):
    return os.environ.get(name, default).strip()


def _env_int(name, default):
    try:
        return int(_env_str(name, str(default)))
    except ValueError:
        return default

def _env_bool(name, default=False):
    value = os.environ.get(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def _env_list(name, default=""):
    return [
        item.strip()
        for item in _env_str(name, default).split(",")
        if item.strip()
    ]


def _env_float(name, default):
    try:
        return float(_env_str(name, str(default)))
    except ValueError:
        return default


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# W-010: DEBUG and ALLOWED_HOSTS come from the environment.
# DEBUG is OFF unless DJANGO_DEBUG=True is set explicitly.
# (DEBUG is read first because the SECRET_KEY rule below depends on it.)
DEBUG = _env_bool("DJANGO_DEBUG", False)

# ---------------------------------------------------------------------
# SECRET_KEY (security review #1)
#
# Django signs sessions and password-reset links with this key, so a
# server must never run with the value published in the repository.
#
# Order of precedence (nothing ever refuses to start):
#   1. DJANGO_SECRET_KEY from the environment / .env  -> used as-is.
#   2. DEBUG=True (local laptop)                       -> dev-only key,
#                                                         same as before.
#   3. Otherwise -> a random key generated ONCE and saved to
#      backend/.secret_key (git-ignored). Every process on this machine
#      (runserver, watcher subprocess, scheduler, backups) reads the
#      same file, so they all share one key.
#
# DRF login tokens are stored in the database, not signed with this key,
# so the React app is unaffected by which key is in use.
# ---------------------------------------------------------------------

_DEV_ONLY_SECRET_KEY = (
    'django-insecure-*3$mgky-th#0y#q%q9l!5^=lv!kk03k58r_+dc5x#j*#oi^+h4'
)

_UNUSABLE_SECRET_KEYS = {
    "",
    "change-me-in-production",
    _DEV_ONLY_SECRET_KEY,
}

_SECRET_KEY_FILE = BASE_DIR / ".secret_key"


def _read_secret_key_file(path):
    try:
        value = path.read_text(encoding="utf-8").strip()
    except OSError:
        return ""
    return "" if value in _UNUSABLE_SECRET_KEYS else value


def _load_or_create_secret_key(path):
    """
    Return the key stored in `path`, creating it once if needed.

    Creation uses O_CREAT | O_EXCL, so if two processes start at the same
    moment only one writes the file and the other reads what it wrote.
    If the folder is not writable, fall back to an in-memory random key:
    the server still starts (sessions just reset on restart).
    """
    existing = _read_secret_key_file(path)
    if existing:
        return existing

    new_key = secrets.token_urlsafe(50)

    try:
        fd = os.open(str(path), os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
    except FileExistsError:
        # Another process created it first (or it held an unusable
        # value): use whatever is there if it is valid.
        return _read_secret_key_file(path) or new_key
    except OSError:
        return new_key

    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            handle.write(new_key)
    except OSError:
        return new_key

    return new_key


SECRET_KEY = _env_str("DJANGO_SECRET_KEY", "")

if SECRET_KEY in _UNUSABLE_SECRET_KEYS:
    if DEBUG:
        SECRET_KEY = _DEV_ONLY_SECRET_KEY
    else:
        SECRET_KEY = _load_or_create_secret_key(_SECRET_KEY_FILE)

ALLOWED_HOSTS = _env_list(
    "DJANGO_ALLOWED_HOSTS",
    "localhost,127.0.0.1",
)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'watcher',
    "corsheaders",
    'django_apscheduler',
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database3
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': _env_str('DB_NAME', 'sec_agent'),
#         'USER': _env_str('DB_USER', 'sec_agent_user'),
#         'PASSWORD': _env_str('DB_PASSWORD'),
#         'HOST': _env_str('DB_HOST', '127.0.0.1'),
#         'PORT': _env_str('DB_PORT', '5433'),
#         'CONN_MAX_AGE': 60,
#         'CONN_HEALTH_CHECKS': True,
#         'OPTIONS': {
#             'connect_timeout': 10,
#         },
#     }
# }

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": _env_str("DB_NAME", "sec_agent"),
        "USER": _env_str("DB_USER", "sec_agent_user"),
        "PASSWORD": _env_str("DB_PASSWORD"),
        "HOST": _env_str("DB_HOST", "127.0.0.1"),
        "PORT": _env_str("DB_PORT", "5433"),
        "CONN_MAX_AGE": 60,
        "CONN_HEALTH_CHECKS": True,
        "OPTIONS": {
            "connect_timeout": 10,
        },

        "TEST": {
            "NAME": "test_sec_agent",
        },
    }
}
if (
    DATABASES["default"]["TEST"]["NAME"]
    == DATABASES["default"]["NAME"]
):
    raise RuntimeError(
        "Unsafe database configuration: "
        "test database must be different from the application database."
    )

# ---------------------------------------------------------------------
# W-039: cache backend
#
# DRF counts login throttle hits (watcher/api/throttles.py) in the
# Django cache, and the schedule view stores the "abort_automation_run"
# flag there. With no CACHES block Django falls back to LocMemCache,
# which is PER PROCESS: under N gunicorn workers each worker keeps its
# own counter, so the effective login limit becomes the configured rate
# times N.
#
# The default below is locmem, which is byte-for-byte what Django was
# already doing, so nothing changes for single-process development.
# Production selects a shared backend with CACHE_BACKEND:
#
#   CACHE_BACKEND=redis     REDIS_URL=redis://127.0.0.1:6379/1
#                           (needs the "redis" package: pip install redis)
#
#   CACHE_BACKEND=database  (no extra package; run once:
#                            python manage.py createcachetable)
#
# watcher/checks.py raises watcher.W001 when DEBUG is off and the
# selected backend is per-process, so this cannot ship silently.
# ---------------------------------------------------------------------

CACHE_BACKEND = _env_str("CACHE_BACKEND", "locmem").lower()

if CACHE_BACKEND == "redis":
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": _env_str(
                "REDIS_URL",
                "redis://127.0.0.1:6379/1",
            ),
        }
    }

elif CACHE_BACKEND == "database":
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.db.DatabaseCache",
            "LOCATION": _env_str(
                "CACHE_TABLE_NAME",
                "django_cache_table",
            ),
        }
    }

else:
    # Unchanged default. Shared only within one process.
    CACHES = {
        "default": {
            "BACKEND": (
                "django.core.cache.backends.locmem.LocMemCache"
            ),
            "LOCATION": _env_str(
                "CACHE_LOCATION",
                "watcher-default",
            ),
        }
    }

# Backends that cannot be shared between processes. Read by
# watcher/checks.py; kept here so the list lives next to the config.
PER_PROCESS_CACHE_BACKENDS = (
    "django.core.cache.backends.locmem.LocMemCache",
    "django.core.cache.backends.dummy.DummyCache",
)

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = "America/New_York"
USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ---------------------------------------------------------------------
# SEC EDGAR settings
#
# SEC_USER_AGENT is REQUIRED by SEC fair-access policy.
# Set it in backend/.env, e.g.:
#
#   SEC_USER_AGENT=Vikram Sethi vikram.sethi@onesmarter.com
#
# It is intentionally NOT validated here: raising in settings.py would
# break every management command, including ones that never touch SEC.
# SECClient raises a clear ImproperlyConfigured instead.
# ---------------------------------------------------------------------

SEC_USER_AGENT = _env_str('SEC_USER_AGENT')

# (connect timeout, read timeout) in seconds - never None, never infinite.
SEC_REQUEST_TIMEOUT = (
    _env_float('SEC_CONNECT_TIMEOUT', 10.0),
    _env_float('SEC_READ_TIMEOUT', 30.0),
)

# Total attempts per request (1 = no retry).
SEC_MAX_RETRIES = _env_int('SEC_MAX_RETRIES', 4)

# Minimum seconds between SEC requests. SEC allows ~10 req/sec.
SEC_MIN_REQUEST_INTERVAL = _env_float('SEC_MIN_REQUEST_INTERVAL', 0.15)

# Cap on how many EDGAR full-text-search hits we page through.
SEC_SEARCH_MAX_RESULTS = _env_int('SEC_SEARCH_MAX_RESULTS', 200)

# Downloads are anchored to BASE_DIR so they do not depend on the
# current working directory.
SEC_DOWNLOAD_DIR = Path(
    _env_str('SEC_DOWNLOAD_DIR') or str(BASE_DIR / 'downloads')
)

# ---------------------------------------------------------------------
# Ticker input file
#
# Production watcher reads ticker symbols from one configured file.
# Keep the path outside application code so deployments can change
# the input location without modifying Python files.
# ---------------------------------------------------------------------

SEC_TICKER_FILE = Path(
    _env_str("SEC_TICKER_FILE")
    or str(BASE_DIR / "tickers.txt")
)
import os


SEC_EMAIL_NOTIFICATIONS_ENABLED = (
    os.getenv(
        "SEC_EMAIL_NOTIFICATIONS_ENABLED",
        "False",
    ).strip().lower()
    == "true"
)


EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

EMAIL_HOST = os.getenv("SMTP_HOST", "")

EMAIL_PORT = int(
    os.getenv("SMTP_PORT", "587")
)

EMAIL_HOST_USER = os.getenv(
    "SMTP_USERNAME",
    "",
)

EMAIL_HOST_PASSWORD = os.getenv(
    "SMTP_PASSWORD",
    "",
)

SMTP_SECURITY = os.getenv(
    "SMTP_SECURITY",
    "STARTTLS",
).strip().upper()


EMAIL_USE_TLS = SMTP_SECURITY in {
    "STARTTLS",
    "TLS",
}

EMAIL_USE_SSL = SMTP_SECURITY == "SSL"

# Set a timeout so we don't hang indefinitely if SMTP host is unreachable
EMAIL_TIMEOUT = 10



DEFAULT_FROM_EMAIL = os.getenv(
    "SMTP_SENDER_EMAIL",
    "",
)

SEC_EMAIL_SENDER_NAME = os.getenv(
    "SMTP_SENDER_NAME",
    "SEC Filing Watcher",
)

SEC_REPLY_TO_EMAIL = os.getenv(
    "SMTP_REPLY_TO_EMAIL",
    "",
)

SEC_ALERT_RECIPIENT_EMAIL = os.getenv(
    "SEC_ALERT_RECIPIENT_EMAIL",
    "",
)
CORS_ALLOWED_ORIGINS = _env_list(
    "CORS_ALLOWED_ORIGINS",
    "http://localhost:5173,http://127.0.0.1:5173",
)

# ---------------------------------------------------------------------
# W-010: every API view requires a token by default.
#
# Clients send:  Authorization: Token <key>
# Admin-only actions add IsAdminUser on the view itself.
# ---------------------------------------------------------------------

# Security review #3: how long a login token stays valid, in hours.
TOKEN_TTL_HOURS = _env_int("TOKEN_TTL_HOURS", 12)

# ---------------------------------------------------------------------
# I-07: the session token is delivered as an HttpOnly cookie.
#
# JavaScript cannot read an HttpOnly cookie, so an XSS payload can no
# longer steal the token and replay the session from another machine.
#
# AUTH_COOKIE_SECURE
#   A Secure cookie is ONLY sent over https. Left on in local http
#   development it silently 401s every request after login: the browser
#   accepts the cookie, then refuses to send it back.
#
#     development (http://localhost)  AUTH_COOKIE_SECURE=False  <- default
#     production  (https://)          AUTH_COOKIE_SECURE=True   <- REQUIRED
#
#   The default is False so a fresh checkout works on localhost. The
#   deployment .env MUST set it True, or the session cookie travels in
#   clear over the network.
#
# AUTH_COOKIE_SAMESITE
#   Lax is correct while the browser is SAME-ORIGIN with the API: the
#   Vite proxy forwards /api/* in development, and production serves
#   the frontend and the API from one host. The browser then never
#   attaches this cookie to a cross-site request, which is what makes
#   CSRF a non-issue here.
#
#   If the frontend is ever served from a DIFFERENT origin, this needs
#   SameSite=None AND AUTH_COOKIE_SECURE=True AND
#   CORS_ALLOW_CREDENTIALS=True AND withCredentials on the axios
#   client. All four together, or the session silently stops working.
# ---------------------------------------------------------------------

AUTH_COOKIE_NAME = _env_str("AUTH_COOKIE_NAME", "watcher_auth")
AUTH_COOKIE_SAMESITE = _env_str("AUTH_COOKIE_SAMESITE", "Lax")
AUTH_COOKIE_SECURE = _env_bool("AUTH_COOKIE_SECURE", False)

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        # Security review #3: tokens expire after TOKEN_TTL_HOURS.
        "watcher.api.authentication.ExpiringTokenAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    # Login brute-force protection. Used only by the throttles on
    # POST /api/auth/login/ (watcher/api/throttles.py); no global
    # DEFAULT_THROTTLE_CLASSES, so other endpoints are not limited.
    "DEFAULT_THROTTLE_RATES": {
        "login_ip": _env_str("LOGIN_RATE_IP", "10/minute"),
        "login_user": _env_str("LOGIN_RATE_USER", "5/minute"),
    },
}

# ---------------------------------------------------------------------
# Event study entry rule
#
# T_PLUS_1:
# Filing accepted today -> next trading session close
#
# SAME_SESSION:
# Filing accepted before close -> same session close
# ---------------------------------------------------------------------

ENTRY_RULE = _env_str(
    "ENTRY_RULE",
    "T_PLUS_1",
)