"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# ---------------------------------------------------------------------
# .env loading
#
# This project has NO python-dotenv dependency (see requirements.txt),
# so we load backend/.env with the standard library only.
#
# Rules:
#   - real environment variables always win over .env
#   - blank lines and "#" comments are ignored
#   - "export KEY=value" is accepted
#   - surrounding single/double quotes are stripped
# ---------------------------------------------------------------------

def _load_env_file(env_path: Path) -> None:
    if not env_path.is_file():
        return

    try:
        raw_text = env_path.read_text(encoding="utf-8-sig")
    except (OSError, UnicodeDecodeError):
        return

    for raw_line in raw_text.splitlines():
        line = raw_line.strip()

        if not line or line.startswith("#"):
            continue

        if line.lower().startswith("export "):
            line = line[len("export "):].strip()

        if "=" not in line:
            continue

        key, _, value = line.partition("=")

        key = key.strip()
        value = value.strip()

        if len(value) >= 2 and value[0] == value[-1] and value[0] in ("'", '"'):
            value = value[1:-1]

        if key and key not in os.environ:
            os.environ[key] = value


_load_env_file(BASE_DIR / ".env")


def _env_str(name, default=""):
    return os.environ.get(name, default).strip()


def _env_int(name, default):
    try:
        return int(_env_str(name, str(default)))
    except ValueError:
        return default


def _env_float(name, default):
    try:
        return float(_env_str(name, str(default)))
    except ValueError:
        return default


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = _env_str(
    'DJANGO_SECRET_KEY',
    'django-insecure-*3$mgky-th#0y#q%q9l!5^=lv!kk03k58r_+dc5x#j*#oi^+h4',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'watcher',
    "corsheaders",
    'django_apscheduler',
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database3
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': _env_str('DB_NAME', 'sec_agent'),
#         'USER': _env_str('DB_USER', 'sec_agent_user'),
#         'PASSWORD': _env_str('DB_PASSWORD'),
#         'HOST': _env_str('DB_HOST', '127.0.0.1'),
#         'PORT': _env_str('DB_PORT', '5433'),
#         'CONN_MAX_AGE': 60,
#         'CONN_HEALTH_CHECKS': True,
#         'OPTIONS': {
#             'connect_timeout': 10,
#         },
#     }
# }

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": _env_str("DB_NAME", "sec_agent"),
        "USER": _env_str("DB_USER", "sec_agent_user"),
        "PASSWORD": _env_str("DB_PASSWORD"),
        "HOST": _env_str("DB_HOST", "127.0.0.1"),
        "PORT": _env_str("DB_PORT", "5433"),
        "CONN_MAX_AGE": 60,
        "CONN_HEALTH_CHECKS": True,
        "OPTIONS": {
            "connect_timeout": 10,
        },

        "TEST": {
            "NAME": "test_sec_agent",
        },
    }
}
if (
    DATABASES["default"]["TEST"]["NAME"]
    == DATABASES["default"]["NAME"]
):
    raise RuntimeError(
        "Unsafe database configuration: "
        "test database must be different from the application database."
    )
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ---------------------------------------------------------------------
# SEC EDGAR settings
#
# SEC_USER_AGENT is REQUIRED by SEC fair-access policy.
# Set it in backend/.env, e.g.:
#
#   SEC_USER_AGENT=Vikram Sethi vikram.sethi@onesmarter.com
#
# It is intentionally NOT validated here: raising in settings.py would
# break every management command, including ones that never touch SEC.
# SECClient raises a clear ImproperlyConfigured instead.
# ---------------------------------------------------------------------

SEC_USER_AGENT = _env_str('SEC_USER_AGENT')

# (connect timeout, read timeout) in seconds - never None, never infinite.
SEC_REQUEST_TIMEOUT = (
    _env_float('SEC_CONNECT_TIMEOUT', 10.0),
    _env_float('SEC_READ_TIMEOUT', 30.0),
)

# Total attempts per request (1 = no retry).
SEC_MAX_RETRIES = _env_int('SEC_MAX_RETRIES', 4)

# Minimum seconds between SEC requests. SEC allows ~10 req/sec.
SEC_MIN_REQUEST_INTERVAL = _env_float('SEC_MIN_REQUEST_INTERVAL', 0.15)

# Cap on how many EDGAR full-text-search hits we page through.
SEC_SEARCH_MAX_RESULTS = _env_int('SEC_SEARCH_MAX_RESULTS', 200)

# Downloads are anchored to BASE_DIR so they do not depend on the
# current working directory.
SEC_DOWNLOAD_DIR = Path(
    _env_str('SEC_DOWNLOAD_DIR') or str(BASE_DIR / 'downloads')
)

# ---------------------------------------------------------------------
# Ticker input file
#
# Production watcher reads ticker symbols from one configured file.
# Keep the path outside application code so deployments can change
# the input location without modifying Python files.
# ---------------------------------------------------------------------

SEC_TICKER_FILE = Path(
    _env_str("SEC_TICKER_FILE")
    or str(BASE_DIR / "tickers.txt")
)
import os


SEC_EMAIL_NOTIFICATIONS_ENABLED = (
    os.getenv(
        "SEC_EMAIL_NOTIFICATIONS_ENABLED",
        "False",
    ).strip().lower()
    == "true"
)


EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

EMAIL_HOST = os.getenv("SMTP_HOST", "")

EMAIL_PORT = int(
    os.getenv("SMTP_PORT", "587")
)

EMAIL_HOST_USER = os.getenv(
    "SMTP_USERNAME",
    "",
)

EMAIL_HOST_PASSWORD = os.getenv(
    "SMTP_PASSWORD",
    "",
)

SMTP_SECURITY = os.getenv(
    "SMTP_SECURITY",
    "STARTTLS",
).strip().upper()


EMAIL_USE_TLS = SMTP_SECURITY in {
    "STARTTLS",
    "TLS",
}

EMAIL_USE_SSL = SMTP_SECURITY == "SSL"

# Set a timeout so we don't hang indefinitely if SMTP host is unreachable
EMAIL_TIMEOUT = 10

EMAIL_USE_SSL = SMTP_SECURITY == "SSL"


DEFAULT_FROM_EMAIL = os.getenv(
    "SMTP_SENDER_EMAIL",
    "",
)

SEC_EMAIL_SENDER_NAME = os.getenv(
    "SMTP_SENDER_NAME",
    "SEC Filing Watcher",
)

SEC_REPLY_TO_EMAIL = os.getenv(
    "SMTP_REPLY_TO_EMAIL",
    "",
)

SEC_ALERT_RECIPIENT_EMAIL = os.getenv(
    "SEC_ALERT_RECIPIENT_EMAIL",
    "",
)
CORS_ALLOWED_ORIGINS = [

    "http://localhost:5173",

]

# ---------------------------------------------------------------------
# Event study entry rule
#
# T_PLUS_1:
# Filing accepted today -> next trading session close
#
# SAME_SESSION:
# Filing accepted before close -> same session close
# ---------------------------------------------------------------------

ENTRY_RULE = _env_str(
    "ENTRY_RULE",
    "T_PLUS_1",
)